group: CelebA
env:
  patch_size: 32
  max_ep_len: 20
data:
  batch_size: 600
  num_workers: 0
  dataset: celeba
  fill_mode: resize # Either "resize" or "pad"
  path: ./.data
model:
  n_channels: 3
  n_tokens: 2
  embedding_size: 32
  gru_hidden_size: 22
  gru_num_layers: 2
  jump_size: 1
optimizer:
  learning_rate: 1.0e-5
reinforce:
  n_iterations: 8000
  log_every: 50
  plot_every: 500
device: auto
mode: online
hydra:
  job:
    chdir: true
