group: CelebA
env:
  patch_size: 32
  max_ep_len: 10
data:
  batch_size: 64
  num_workers: 0
  dataset: celeba
  path: ./.data
model:
  n_channels: [3, 5, 10, 25]
  kernels: [3, 3, 3]
  maxpools: [true, true, true]
  embedding_size: 64
  n_layers_mlp: 1
  gru_hidden_size: 44
  gru_num_layers: 4
  maximum_steps: 3
optimizer:
  learning_rate: 1.0e-4
reinforce:
  n_iterations: 8000
  log_every: 50
  plot_every: 500
device: auto
hydra:
  job:
    chdir: true
