group: LARD
env:
  patch_size: 224
  max_ep_len: 20
data:
  batch_size: 8
  num_workers: 0
  dataset: standard
  path: ./.data/LARD/
model:
  n_channels: [3, 5, 10, 15, 20, 25]
  kernels: [5, 5, 5, 5, 3]
  embedding_size: 92
  gru_hidden_size: 64
  gru_num_layers: 4
optimizer:
  learning_rate: 1.0e-5
reinforce:
  n_iterations: 8000
  log_every: 50
  plot_every: 500
device: auto
hydra:
  job:
    chdir: true
