group: LARD
env:
  patch_size: 224
  max_ep_len: 20
data:
  batch_size: 32
  num_workers: 4
  dataset: standard
  path: /data1/pierrep/jolineedle/runway_LARD/
model:
  n_channels: [3, 5, 10, 25]
  kernels: [3, 3, 3]
  embedding_size: 64
  gru_hidden_size: 44
  gru_num_layers: 4
optimizer:
  learning_rate: 1.0e-4
reinforce:
  n_iterations: 8000
  plot_every: 500
device: auto
hydra:
  job:
    chdir: true
