group: LARD
env:
  patch_size: 224
  max_ep_len: 40
data:
  batch_size: 16
  num_workers: 4
  dataset: standard
  path: ./.data/lard_dataset/lard/1.0.0/
model:
  n_channels: [3, 5, 10, 15, 20, 25]
  kernels: [5, 5, 5, 5, 3]
  maxpools: [true, true, true, true, true]
  embedding_size: 128
  n_layers_mlp: 4
  gru_hidden_size: 92
  gru_num_layers: 4
optimizer:
  learning_rate: 1.0e-5
reinforce:
  n_iterations: 100000
  log_every: 50
  plot_every: 500
device: auto
hydra:
  job:
    chdir: true
