group: LARD
env:
  patch_size: 224
  max_ep_len: 40
data:
  batch_size: 42
  num_workers: 0
  dataset: standard
  fill_mode: resize # Either "resize" or "pad"
  path: ./.data/lard_dataset/lard/1.0.0/
model:
  n_channels: 3
  vit_num_tokens: 7
  vit_hidden_size: 64
  vit_num_layers: 6
  gru_hidden_size: 128
  gru_num_layers: 4
  jump_size: 1
optimizer:
  learning_rate: 1.0e-5
reinforce:
  entropy_weight: 1.0e-2
  n_iterations: 200000
  log_every: 100
  plot_every: 500
device: auto
mode: online
hydra:
  job:
    chdir: true
